name: Tests for hw2
on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    env:
      VALGRIND_OPTS: --leak-check=full --track-origins=yes --show-leak-kinds=all
      CPPLINT_FILTERS: --filter=-build/include_subdir,-readability/casting,-legal/copyright,-build/include_subdir,-whitespace/line_length,-runtime/threadsafe_fn,-build/include,-build/header_guard
      CPPLINT_FILES: --recursive main.c lib/src/ lib/include/ test/
      CPPCHECK_FILES: main.c generator.c generate_data.c test/ lib/include lib/src

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update & install packages
        run: |
         apt update && apt upgrade -y && apt install -y gcc-10 cmake g++-10 build-essential cppcheck valgrind python3 python3-pip
         python3 -m pip install cpplint

      - name: Run cpplint
        run: cpplint $CPPLINT_FILTERS $CPPLINT_FILES

      - name: Run cppcheck
        run: cppcheck $CPPCHECK_FILES

      - name: Compile libs
        run: cd lib && cmake . -DCMAKE_INSTALL_PREFIX=~/install && make -j$(nproc)

      - name: Install libs
        run: cd lib && cmake --build . --target install

      - name: Make project
        run: cmake . -Dsingle_DIR=~/install/lib/cmake/Single -Dmulti_DIR=~/install/lib/cmake/Multi && make -j$(nproc)

      - name: Run gtest
        run: make test

      - name: Run Valgrind on target multi
        run: valgrind $VALGRIND_OPTS ./hw2_multi

      - name: Run Valgrind on target single
        run: valgrind $VALGRIND_OPTS ./hw2_single

      - name: Single-threaded execution time
        run: time ./hw2_single

      - name: Multi-threaded execution time
        run: time ./hw2_multi
     
      - name: Compile stress data generator
        run: gcc generate_data.c -o generator

      - name: Generate stress data_1
        run: ./generator a > stress1.txt

      - name: Stress single-threaded
        run: ./hw2_single stress1.txt > result1

      - name: Stress multi-threaded
        run: ./hw2_multi stress1.txt > result2

      - name: Compare the result
        run: diff result1 result2 
